package majorproject;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import javax.swing.*;
import java.sql.*;
import java.util.Arrays;

public class SupervisorReport extends javax.swing.JFrame {
Connection cn=null;
String dte=null;
String tm=null;
String blck=null;
String schme=null;
String sc2[]=null;
int[] seat;
   public SupervisorReport() 
   {
       initComponents();
       ImageIcon icon = new ImageIcon("\\Majorproject\\src\\logs\\msbtelogo.jpg");
       jLabel12.setIcon(icon);
       try
       {
            cn = DriverManager.getConnection("jdbc:odbc:gpm");
            Statement st = cn.createStatement();
            t1.addItem("SELECT");
            ResultSet rs = st.executeQuery("select distinct(dt) from seatchart");
            while(rs.next())
            {
                t1.addItem(rs.getString(1));
            }
            t1.addItemListener(new ItemListener()
            {

                @Override
                public void itemStateChanged(ItemEvent e)
                {
                   try
                   {
                        t2.removeAllItems();
                        Statement st = cn.createStatement();
                        ResultSet rs = st.executeQuery("select distinct(session) from seatchart where dt='"+t1.getSelectedItem().toString()+"'");
                        while(rs.next())
                        {
                            t2.addItem(rs.getString(1));
                        }
                   
                   }catch(Exception e1){}
                    
                }
            });
            t2.addItemListener(new ItemListener()
            {

                @Override
                public void itemStateChanged(ItemEvent e)
                {
                   try
                   {
                        jComboBox1.removeAllItems();
                        Statement st = cn.createStatement();
                        ResultSet rs = st.executeQuery("select blockno from seatchart where dt='"+t1.getSelectedItem().toString()+"' and session='"+t2.getSelectedItem().toString()+"'");
                        while(rs.next())
                        {
                            jComboBox1.addItem(rs.getString(1));
                        }
                   
                   }catch(Exception e1){}
                    
                }
            });
           
        
           jComboBox1.addItemListener(new ItemListener()
           {

               @Override
               public void itemStateChanged(ItemEvent e)
               {
                   blck = jComboBox1.getSelectedItem().toString();
                   tm = t2.getSelectedItem().toString();
                   dte = t1.getSelectedItem().toString();
                   jComboBox2.removeAllItems();
                   try
                   {
                       
                         Statement st2 = cn.createStatement();
                         ResultSet rs2 = st2.executeQuery("select * from seatchart where dt='"+dte+"' and session='"+tm+"' and blockno='"+blck+"'");
                         
                         while(rs2.next())
                         {
                            sc2 = rs2.getString(6).split(",");
                         }
                         for(int i=0;i<sc2.length;i++)
                         {
                            jComboBox2.addItem(sc2[i].toUpperCase());
                         }
                         
                   }
                   catch (Exception e1){JOptionPane.showMessageDialog(null,e); }
               }
           });
       }
       catch (Exception e){JOptionPane.showMessageDialog(null,e);}
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t1 = new javax.swing.JComboBox();
        t2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        blcklb = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scheme = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tm1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        blcklb2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sublb = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        totallb = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        scode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seatnolb = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        ta2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(795, 950));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPERVISOR REPORT");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 11, 670, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("BLOCK");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(480, 10, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SCHEME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 60, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DATE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 34, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("TIME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 10, 30, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(320, 60, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(490, 60, 110, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(630, 60, 110, 30);

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(t1);
        t1.setBounds(60, 10, 150, 30);

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(t2);
        t2.setBounds(270, 10, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(530, 10, 100, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(100, 60, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 760, 110);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MAHARASHTRA STATE BOARD OF TECHNICAL EDUCATION, MUMBAI");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(100, 10, 650, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SUPERVISOR'S REPORT");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel8);
        jLabel8.setBounds(290, 80, 460, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SUPERVISOR BLOCK NO :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 80, 170, 30);

        blcklb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blcklb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blcklb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(blcklb);
        blcklb.setBounds(180, 80, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("YEAR-COURSE-MASTER :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 130, 160, 20);

        scheme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scheme.setText("-");
        jPanel3.add(scheme);
        scheme.setBounds(180, 130, 120, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("DATE :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(330, 130, 50, 20);

        dt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dt.setText("-");
        jPanel3.add(dt);
        dt.setBounds(390, 130, 130, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("TIME");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(550, 130, 40, 20);

        tm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tm1.setText("-");
        jPanel3.add(tm1);
        tm1.setBounds(600, 130, 140, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("NAME OF INSTITUTE : ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 170, 150, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("INSTITUTE CODE :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(490, 170, 120, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("0131");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(620, 170, 40, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("SEAT NO:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 210, 60, 17);

        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 400, 740, 2);

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SEAT NO. OF ABSENT STUDENTS");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel17.setOpaque(true);
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 410, 410, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("OFFICER IN CHARGE");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(570, 730, 160, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("CHECKED BY");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(40, 730, 100, 17);

        blcklb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(blcklb2);
        blcklb2.setBounds(390, 730, 60, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("SUPERVISOR");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(290, 730, 90, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("SUBJECT :");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(30, 320, 70, 30);

        sublb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sublb.setText("-");
        jPanel3.add(sublb);
        sublb.setBounds(100, 320, 650, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("TOTAL :");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(560, 360, 60, 30);

        totallb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totallb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totallb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(totallb);
        totallb.setBounds(630, 360, 100, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("SUBJECT CODE :");
        jLabel29.setToolTipText("");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(30, 360, 110, 30);

        scode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scode.setText("-");
        jPanel3.add(scode);
        scode.setBounds(140, 360, 110, 30);

        seatnolb.setColumns(20);
        seatnolb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seatnolb.setLineWrap(true);
        seatnolb.setRows(5);
        seatnolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(seatnolb);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(80, 210, 670, 91);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 10, 80, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("GOVERNMENT POLYTECHNIC MIRAJ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(160, 160, 270, 40);

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ta1.setLineWrap(true);
        ta1.setRows(5);
        ta1.setWrapStyleWord(true);
        ta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(ta1);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 450, 410, 210);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("TOTAL NUMBERS OF ANSWER BOOKS");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(420, 410, 320, 30);

        ta2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta2.setText("-");
        ta2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(ta2);
        ta2.setBounds(420, 450, 320, 210);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 200, 760, 760);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logs/KPMS.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel28.setInheritsPopupMenu(false);
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 10, 80, 65);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        seatnolb.setText("");
        totallb.setText("");
        schme=jComboBox2.getSelectedItem().toString();
       String tme[] = tm.split(",");
       blcklb.setText(blck);
       blcklb2.setText("("+blck+")");
       scheme.setText(schme);
       dt.setText(dte);
       tm1.setText(tm);
       
        try
        {
            
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from seatchart where dt='"+dte+"' and session='"+tm+"' and blockno='"+blck+"'");
           while(rs.next())
           {
              blockseat1(rs.getString(4),rs.getString(5),rs.getString(6),blck);
           }
           Statement st1 = cn.createStatement();
           ResultSet rs1 = st1.executeQuery("select * from timetable2020 where dt='"+dte+"' and scheme='"+jComboBox2.getSelectedItem().toString()+"'");
           while(rs1.next())
           {
               sublb.setText(rs1.getString("sub"));
               scode.setText(rs1.getString("code"));
           }
           
        }
        catch (Exception e)
        {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
         PrinterJob job = PrinterJob.getPrinterJob();
         job.setJobName("print");
         job.setPrintable(new Printable()
         {

            
             public int print(Graphics pg, PageFormat pf, int pn)         
             {
                 if(pn>0)
                     return Printable.NO_SUCH_PAGE;

                 Graphics2D g2= (Graphics2D)pg;
                 g2.translate(30,30);
                 g2.scale(0.7,0.9);
                 jPanel3.print(g2);
                 
                 return Printable.PAGE_EXISTS;
             }
         });
        if(job.printDialog()==true)
        {
        
            try
            {
                job.print();
            }
            catch(Exception e){}
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        new SupervisorReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        ta2.setText("");
        int tol=Integer.parseInt(totallb.getText());
        String[] t1=ta1.getText().split(",");
        if(tol==t1.length)
        {
            ta2.setText("0");
        }
        else
        {
            ta2.setText(""+(tol-(t1.length)));
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
    public void blockseat1(String start,String end,String scheme,String bno)
    {
       try
        {
            sublb.setText(jComboBox2.getSelectedItem().toString());
            int strt = Integer.parseInt(start);
            int ed = Integer.parseInt(end);
            String sc[]=scheme.split(",");
            int len=0;
            Statement st2 = cn.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from blockstr where blockno='"+bno+"'");
            while(rs2.next())
            {
                len=rs2.getInt(3);
            }
            seat = new int[len];
            int h=0;
            for(int i=0;i<sc.length;i++)
            {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM student2020 WHERE scheme='"+sc[i]+"' and seat between '"+start+"' and '"+end+"'");
                while(rs.next())
                {
                    seat[h]=rs.getInt("seat");
                    h++;
                }
            }
            Arrays.sort(seat);
            int c=0;
            for(int i=0;i<seat.length;i++)
            {
               
                Statement st79 = cn.createStatement();
                ResultSet rs79 = st79.executeQuery("select * from student2020 where seat='"+seat[i]+"'");
                while(rs79.next())
                {
                    
                    if(rs79.getString("scheme").equals(jComboBox2.getSelectedItem().toString()))
                    {
                        
                        
                        if(i==(seat.length-1))
                            seatnolb.setText(seatnolb.getText()+""+seat[i]);
                        else
                            seatnolb.setText(seatnolb.getText()+""+seat[i]+" , ");
                        c++;
                    }
                                         

                }
            }
           
            totallb.setText(""+c);
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);} 
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupervisorReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blcklb;
    private javax.swing.JLabel blcklb2;
    private javax.swing.JLabel dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel scheme;
    private javax.swing.JLabel scode;
    private javax.swing.JTextArea seatnolb;
    private javax.swing.JLabel sublb;
    private javax.swing.JComboBox t1;
    private javax.swing.JComboBox t2;
    private javax.swing.JTextArea ta1;
    private javax.swing.JLabel ta2;
    private javax.swing.JLabel tm1;
    private javax.swing.JLabel totallb;
    // End of variables declaration//GEN-END:variables
}
